### ISSUE TITLE
The speeds are super slow?

### ISSUE THREAD

**Issue by lemire** [ppamorim/simdjson-cocoa#1]
On a recent iPhone, you should achieve ~1GB/s.

**Comment by ppamorim** [comment]
Yes, I agree with you. This project is based on your own sample, the `simdjson.cpp` is the same and I tried to mimic your project configuration. Is there something wrong with my configuration of the C++ compiler on Xcode?

**Comment by lemire** [comment]
In my build settings, I have `"GCC_OPTIMIZATION_LEVEL[sdk=iphoneos12.2]" = s;`. Looking at your project, you do not appear to have the equivalent. This may or may not matter... I am no Xcode expert... but the first thing I would check is that if you have asked the compiler to optimize the code.

One thing you could do is to compile in debug mode, check the performance. Then debug in release mode and check the performance. There should be a large gap between the two.

**Comment by ppamorim** [comment]
@lemire Thank you I will try to solve this problem.

**Comment by ppamorim** [comment]
@lemire Fixed! Thank you very much.
